--CREAMOS LA BASE DE DATOS 

CREATE DATABASE COLEGIO

USE COLEGIO


--CREAMOS LAS TABLAS CON SU RELACION
CREATE TABLE Asignaturas (
Id INT IDENTITY (1,1),
Codigo VARCHAR (5) PRIMARY KEY,
Nombre VARCHAR (40) NOT NULL ,
Creditos TINYINT NOT NULL
)

CREATE TABLE Docentes (
Id INT IDENTITY (1,1),
Codigo VARCHAR (5)  PRIMARY KEY,
Nombre VARCHAR (40) NOT NULL ,
Apellido VARCHAR (40) NOT NULL ,
Cod_Asig VARCHAR (5) NOT NULL
CONSTRAINT FK_DOCENTES_01 FOREIGN KEY
REFERENCES Asignaturas(Codigo)
)


CREATE TABLE Estudiantes (
Id INT IDENTITY (1,1),
Codigo VARCHAR (5) PRIMARY KEY,
Nombre VARCHAR (40) NOT NULL,
Apellido VARCHAR (40)NOT NULL,
Semestre VARCHAR (40)NOT NULL,
Carrera VARCHAR (40)NOT NULL,
Cod_Asig VARCHAR (5) NOT NULL
CONSTRAINT FK_ESTUDIANTES_01 FOREIGN KEY
REFERENCES Asignaturas(Codigo)
)


CREATE TABLE Record (
Id INT IDENTITY (1,1),
Codigo VARCHAR (5)  PRIMARY KEY,
Fecha DATE DEFAULT GETDATE(),
Periodo VARCHAR (40) NOT NULL,
Cod_Est VARCHAR (5) NOT NULL 
CONSTRAINT FK_RECORD_01 FOREIGN KEY
REFERENCES Estudiantes(Codigo),
Cod_Doc VARCHAR (5) NOT NULL 
CONSTRAINT FK_RECORD_02 FOREIGN KEY
REFERENCES Docentes(Codigo),
Nota1 DECIMAL(5,2) NOT NULL,
Nota2 DECIMAL(5,2) NOT NULL,
Promedio AS (Nota1+Nota2)/2 NOT NULL
)

--STORED PROCEDURES ASIGNATURA
--MOSTRAR ASIGNATURA
ALTER  PROCEDURE SP_MOSTRARASIG
AS
 BEGIN
 SELECT * FROM Asignaturas
 END

EXECUTE SP_MOSTRARASIG
--MOSTRAR ASIGNATURA XID 
ALTER PROCEDURE SP_MOSTRARASIGXID(
@id INT)
AS
 BEGIN
 SELECT * FROM Asignaturas WHERE Id = @id
 END
--INSRETAR ASIGNATURA
ALTER PROCEDURE SP_INSERTARASIG(
@Codigo VARCHAR(5),
@Nombre VARCHAR(40),
@Creditos TINYINT
)
 AS BEGIN
	INSERT INTO  Asignaturas(Codigo,Nombre,Creditos)VALUES(@Codigo,@Nombre,@Creditos)
END

EXEC SP_INSERTARASIG 'AS02','ESPAÑOL',3



--ACTUALIZAR ASIGNATURAS
ALTER PROCEDURE SP_ACTUALIZARASIG(
@id INT,
@Codigo VARCHAR(5),
@Nombre VARCHAR(40),
@Creditos TINYINT
)
AS BEGIN
     UPDATE Asignaturas SET Codigo = @Codigo, Nombre = @Nombre, Creditos = @Creditos WHERE Id = @id
    END

--ELIMINAR ASIGNATURA
ALTER PROCEDURE SP_ELIMINARASIG(
@id INT
)
 AS BEGIN
     DELETE Asignaturas WHERE Id = @id
    END

EXECUTE SP_ELIMINARASIG 9

--STORED PROCEDURES DOCENTES
--MOSTRAR DOCENTES
ALTER PROCEDURE SP_MOSTRARDOC
AS
 BEGIN
 SELECT * FROM Docentes
 END
--MOSTRAR DOCENTES XID 
ALTER PROCEDURE SP_MOSTRARDOCENTESXID(
@id INT)
AS
 BEGIN
 SELECT * FROM Docentes WHERE Id = @id
 END


--INSRETAR DOCENTES
ALTER PROCEDURE SP_INSERTARDOC(
@Codigo VARCHAR(5),
@Nombre VARCHAR(40),
@Apellido VARCHAR(40),
@Codigoasig VARCHAR(5)
)
 AS BEGIN
	INSERT INTO  Docentes(Codigo,Nombre,Apellido,Cod_Asig)VALUES(@Codigo,@Nombre,@Apellido,@Codigoasig)
END




--ACTUALIZAR DOCENTES
ALTER PROCEDURE SP_ACTUALIZARDOC(
@id INT,
@Codigo VARCHAR(5),
@Nombre VARCHAR(40),
@Apellido VARCHAR(40),
@Codigoasig VARCHAR(5)
)
AS BEGIN
   UPDATE Docentes SET Codigo=@Codigo, Nombre=@Nombre,Apellido=@Apellido,Cod_Asig=@Codigoasig  WHERE Id = @id
   END
--ELIMINAR DOCENTE
ALTER PROCEDURE SP_ELIMINARDOC(
@id INT
)
 AS BEGIN
     DELETE Docentes WHERE Id = @id
    END
EXECUTE SP_ELIMINARDOC 6


--STORED PROCEDURES ESTUDIANTES
--MOSTRAR ESTUDIANTES
ALTER PROCEDURE SP_MOSTRAREST
AS
 BEGIN
 SELECT * FROM Estudiantes
 END
--MOSTRAR ESTUDIANTES XID 
ALTER PROCEDURE SP_MOSTRARESTXID(
@id INT)
AS
 BEGIN
 SELECT * FROM Estudiantes WHERE Id = @id
 END
--INSRETAR ESTUDIANTES
ALTER PROCEDURE SP_INSERTAREST(
@Codigo VARCHAR(5),
@Nombre VARCHAR(40),
@Apellido VARCHAR(40),
@Semestre VARCHAR (40),
@Carrera VARCHAR (40),
@Codigoasig VARCHAR(5)
)
 AS BEGIN
	INSERT INTO  Estudiantes(Codigo,Nombre,Apellido,Semestre,Carrera,Cod_Asig)
	VALUES(@Codigo,@Nombre,@Apellido,@Semestre,@Carrera,@Codigoasig)
END
--ACTUALIZAR ESTUDUANTES
ALTER PROCEDURE SP_ACTUALIZAREST(
@id INT,
@Codigo VARCHAR(5),
@Nombre VARCHAR(40),
@Apellido VARCHAR(40),
@Semestre VARCHAR (40),
@Carrera VARCHAR (40),
@Codigoasig VARCHAR(5)
)
AS BEGIN
   UPDATE Estudiantes SET Codigo=@Codigo, Nombre=@Nombre,Apellido=@Apellido,Semestre=@Semestre,Carrera=@Carrera,   
   COD_ASIG=@Codigoasig  
   WHERE Id = @id
   END
--ELIMINAR ESTUDIANTES
ALTER PROCEDURE SP_ELIMINAREST(
@id INT
)
 AS BEGIN
     DELETE Estudiantes WHERE Id = @id
    END



--STORED PROCEDURES RECORD
--MOSTRAR RECORD
ALTER PROCEDURE SP_MOSTRARREC
AS
 BEGIN
 SELECT * FROM Record
 END

EXEC SP_MOSTRARREC
--MOSTRAR RECORD XID 
ALTER PROCEDURE SP_MOSTRARRECXID(
@id INT)
AS
 BEGIN
 SELECT * FROM Record WHERE Id = @id
 END

--INSRETAR RECORD
ALTER PROCEDURE SP_INSERTARREC(
@Codigo VARCHAR(5),
@Periodo VARCHAR(40),
@Codest VARCHAR(5),
@Coddoc VARCHAR(5),
@Nota1 DECIMAL(5,2),
@Nota2 DECIMAL(5,2)
)
 AS BEGIN
	INSERT INTO  Record(Codigo,Periodo,Cod_Est,Cod_Doc,Nota1,Nota2)
	VALUES(@Codigo,@Periodo,@Codest,@Coddoc,@Nota1 ,@Nota2)
END


EXECUTE SP_INSERTARREC 'REC03','CUARTO','DOC01','EST01',5,5
EXECUTE SP_INSERTARREC 'REC04','PRIMERO','DOC01','EST01',1,3
EXECUTE SP_INSERTARREC 'REC08','TERCERO','DOC01','EST02',2,2



--ACTUALIZAR RECORD
ALTER PROCEDURE SP_ACTUALIZARREC(
@id INT,
@Codigo VARCHAR(5),
@Periodo VARCHAR(40),
@Codest VARCHAR(5),
@Coddoc VARCHAR(5),
@Nota1 DECIMAL(5,2),
@Nota2 DECIMAL(5,2)
)
AS BEGIN
   UPDATE Record SET Codigo=@Codigo, Periodo=@Periodo,Cod_Est=@Codest,Cod_Doc=@Coddoc,Nota1=@Nota1,Nota2=@Nota2   
   WHERE Id = @id
   END

--ELIMINAR RECORD
ALTER PROCEDURE SP_ELIMINARREC(
@id INT
)
 AS BEGIN
     DELETE Record WHERE Id = @id
    END

EXECUTE SP_ELIMINARREC 19









